packages:
    - "apps/*"
    - "packages/*"
allowBuilds:
    esbuild: true
catalog:
    "@better-auth/expo": ^1.7.2
    "@biomejs/biome": ^2.5.11
    "@orpc/server": ^1.15.0
    "@types/node": ^26.4.0
    "@types/pg": ^8.23.1
    auth: ^1.7.2
    better-auth: ^1.7.2
    dotenv: ^17.4.2
    dotenv-cli: ^11.0.0
    drizzle-kit: ^0.31.10
    drizzle-orm: ^0.45.2
    pg: ^8.23.0
    typescript: 7.0.2
    zod: ^4.4.3
catalogs:
    expo:
        expo-network: ~57.0.1
        expo-secure-store: ~57.0.2
        typescript: ~6.0.3
minimumReleaseAgeExclude:
    - "@biomejs/biome@2.5.11"
    - "@biomejs/cli-darwin-arm64@2.5.11"
    - "@biomejs/cli-darwin-x64@2.5.11"
    - "@biomejs/cli-linux-arm64-musl@2.5.11"
    - "@biomejs/cli-linux-arm64@2.5.11"
    - "@biomejs/cli-linux-x64-musl@2.5.11"
    - "@biomejs/cli-linux-x64@2.5.11"
    - "@biomejs/cli-win32-arm64@2.5.11"
    - "@biomejs/cli-win32-x64@2.5.11"
    - "@types/node@26.4.0"
